set_property SRC_FILE_INFO {cfile:/home/michal/Downloads/SoC_p2_zc706/p2_constraints.xdc rfile:../../../../p2_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVDS} [get_ports SYS_CLK_0_clk_p]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G9 IOSTANDARD LVDS} [get_ports SYS_CLK_0_clk_n]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 -name sys_clk_pin -add [get_ports SYS_CLK_0_clk_p]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK25 IOSTANDARD LVCMOS25} [get_ports reset]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y20 IOSTANDARD LVCMOS25} [get_ports UART_0_dtr]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS25} [get_ports UART_0_cts]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC18 IOSTANDARD LVCMOS25} [get_ports UART_0_txd]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC19 IOSTANDARD LVCMOS25} [get_ports UART_0_rxd]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ21 IOSTANDARD LVCMOS25} [get_ports UART_1_dtr]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK21 IOSTANDARD LVCMOS25} [get_ports UART_1_cts]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS25} [get_ports UART_1_txd]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS25} [get_ports UART_1_rxd]
