# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/michal/Downloads/SoC_p2_zc706/p2_constraints.xdc

# Block Designs: bd/p2_ddr3/p2_ddr3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3 || ORIG_REF_NAME==p2_ddr3} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_mig_7series_0_0/p2_ddr3_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_mig_7series_0_0 || ORIG_REF_NAME==p2_ddr3_mig_7series_0_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_axi_bram_ctrl_0_0/p2_ddr3_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_axi_bram_ctrl_0_0 || ORIG_REF_NAME==p2_ddr3_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_axi_bram_ctrl_0_bram_0/p2_ddr3_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==p2_ddr3_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_axi_clock_converter_0_0/p2_ddr3_axi_clock_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_axi_clock_converter_0_0 || ORIG_REF_NAME==p2_ddr3_axi_clock_converter_0_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_axi_uart16550_0_0/p2_ddr3_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_axi_uart16550_0_0 || ORIG_REF_NAME==p2_ddr3_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_smartconnect_0_0/p2_ddr3_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_smartconnect_0_0 || ORIG_REF_NAME==p2_ddr3_smartconnect_0_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_xilinx_jtag_0_0/p2_ddr3_xilinx_jtag_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_xilinx_jtag_0_0 || ORIG_REF_NAME==p2_ddr3_xilinx_jtag_0_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_mkP2_Core_1_0/p2_ddr3_mkP2_Core_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_mkP2_Core_1_0 || ORIG_REF_NAME==p2_ddr3_mkP2_Core_1_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_system_ila_0_1/p2_ddr3_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_system_ila_0_1 || ORIG_REF_NAME==p2_ddr3_system_ila_0_1} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_rst_p2_ddr3_50M_0/p2_ddr3_rst_p2_ddr3_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_rst_p2_ddr3_50M_0 || ORIG_REF_NAME==p2_ddr3_rst_p2_ddr3_50M_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_xlconcat_0_0/p2_ddr3_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_xlconcat_0_0 || ORIG_REF_NAME==p2_ddr3_xlconcat_0_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_axi_uart16550_1_0/p2_ddr3_axi_uart16550_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_axi_uart16550_1_0 || ORIG_REF_NAME==p2_ddr3_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/p2_ddr3/ip/p2_ddr3_xlconstant_0_0/p2_ddr3_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==p2_ddr3_xlconstant_0_0 || ORIG_REF_NAME==p2_ddr3_xlconstant_0_0} -quiet] -quiet

# XDC: /home/michal/Downloads/SoC_p2_zc706/SoC_p2_zc706/SoC_p2_zc706.gen/sources_1/bd/p2_ddr3/p2_ddr3_ooc.xdc
