# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/michal/Downloads/SoC_p2_zc706/SoC_p2_zc706/SoC_p2_zc706.srcs/sources_1/bd/p2_ddr3/ip/p2_ddr3_rst_p2_ddr3_50M_0/p2_ddr3_rst_p2_ddr3_50M_0.xci
# IP: The module: 'p2_ddr3_rst_p2_ddr3_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/michal/Downloads/SoC_p2_zc706/SoC_p2_zc706/SoC_p2_zc706.gen/sources_1/bd/p2_ddr3/ip/p2_ddr3_rst_p2_ddr3_50M_0/p2_ddr3_rst_p2_ddr3_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'p2_ddr3_rst_p2_ddr3_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/michal/Downloads/SoC_p2_zc706/SoC_p2_zc706/SoC_p2_zc706.gen/sources_1/bd/p2_ddr3/ip/p2_ddr3_rst_p2_ddr3_50M_0/p2_ddr3_rst_p2_ddr3_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'p2_ddr3_rst_p2_ddr3_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/michal/Downloads/SoC_p2_zc706/SoC_p2_zc706/SoC_p2_zc706.gen/sources_1/bd/p2_ddr3/ip/p2_ddr3_rst_p2_ddr3_50M_0/p2_ddr3_rst_p2_ddr3_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'p2_ddr3_rst_p2_ddr3_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/michal/Downloads/SoC_p2_zc706/SoC_p2_zc706/SoC_p2_zc706.srcs/sources_1/bd/p2_ddr3/ip/p2_ddr3_rst_p2_ddr3_50M_0/p2_ddr3_rst_p2_ddr3_50M_0.xci
# IP: The module: 'p2_ddr3_rst_p2_ddr3_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/michal/Downloads/SoC_p2_zc706/SoC_p2_zc706/SoC_p2_zc706.gen/sources_1/bd/p2_ddr3/ip/p2_ddr3_rst_p2_ddr3_50M_0/p2_ddr3_rst_p2_ddr3_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'p2_ddr3_rst_p2_ddr3_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/michal/Downloads/SoC_p2_zc706/SoC_p2_zc706/SoC_p2_zc706.gen/sources_1/bd/p2_ddr3/ip/p2_ddr3_rst_p2_ddr3_50M_0/p2_ddr3_rst_p2_ddr3_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'p2_ddr3_rst_p2_ddr3_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/michal/Downloads/SoC_p2_zc706/SoC_p2_zc706/SoC_p2_zc706.gen/sources_1/bd/p2_ddr3/ip/p2_ddr3_rst_p2_ddr3_50M_0/p2_ddr3_rst_p2_ddr3_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'p2_ddr3_rst_p2_ddr3_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
